// Loon脚本 - 修改大学搜题酱VIP状态
// 名称：大学搜题酱VIP修改
// 描述：修改用户VIP状态为会员，解锁VIP功能
// 作者：Generated by AI
// 更新时间：2024-01-20

const targetHost = 'www.daxuesoutijiang.com';
const targetPath = '/capi/user/userinfo';

let body = $response.body;

if ($request.url.indexOf(targetPath) !== -1) {
    try {
        let obj = JSON.parse(body);
        
        // 修改VIP相关字段
        if (obj.data) {
            obj.data.isVip = 1;                    // VIP状态：1表示VIP
            obj.data.upGradeFlag = false;          // 关闭升级提示
            obj.data.points = 9999;                // 设置积分
            obj.data.grade = 100;                  // 设置等级
            obj.data.gradeName = "毕业";           // 设置等级名称
            
            // 可选：修改其他用户信息
            // obj.data.nickName = "VIP用户";
            // obj.data.educationValue = "大学本科";
        }
        
        body = JSON.stringify(obj);
        console.log("VIP状态修改成功");
        
    } catch (e) {
        console.log("JSON解析错误: " + e);
    }
}

$done({body});
